import "./globals.css";
import SessionProviderWrapper from '@/components/provider/SessionProviderWrapper';
import ReduxProvider from "@/components/provider/ReduxProvider";
import { SocketProvider } from '@/components/provider/SocketProvider';

import LoadingSpinner from "@/components/LoadingSpinner";
import Toast from "@/components/Toast";
import './toast.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          <ReduxProvider>
            <SocketProvider>
              <LoadingSpinner />
              <Toast />
              {children}
            </SocketProvider>
          </ReduxProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
